import { AiFillStar } from "react-icons/ai";
import React from "react";

const data = [
  
  {
    img: "",
    title: "Engineering Mathematics-I",
    star: <AiFillStar className="rating-star" />,
    reviews: "(210 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "1st",
    semester: "1st semester",
    branch: "Computer Science",
  },
  {
    img: "",
    title: "Basic Electrical Engineering",
    star: <AiFillStar className="rating-star" />,
    reviews: "(190 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "1st",
    semester: "1st semester",
    branch: "Electrical Engineering",
  },
  {
    img: "",
    title: "Engineering Physics",
    star: <AiFillStar className="rating-star" />,
    reviews: "(185 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "1st",
    semester: "1st semester",
    branch: "Information Technology",
  },
  {
    img: "",
    title: "Engineering Mechanics",
    star: <AiFillStar className="rating-star" />,
    reviews: "(170 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "1st",
    semester: "1st semester",
    branch: "Civil Engineering",
  },

  
  {
    img: "",
    title: "Data Structures",
    star: <AiFillStar className="rating-star" />,
    reviews: "(342 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "2nd",
    semester: "3rd semester",
    branch: "Computer Science",
  },
  {
    img: "",
    title: "Digital Logic Design",
    star: <AiFillStar className="rating-star" />,
    reviews: "(224 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "2nd",
    semester: "3rd semester",
    branch: "Electrical Engineering",
  },
  {
    img: "",
    title: "Object-Oriented Programming",
    star: <AiFillStar className="rating-star" />,
    reviews: "(288 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "2nd",
    semester: "3rd semester",
    branch: "Information Technology",
  },
  {
    img: "",
    title: "Surveying",
    star: <AiFillStar className="rating-star" />,
    reviews: "(156 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "2nd",
    semester: "3rd semester",
    branch: "Civil Engineering",
  },

  {
    img: "",
    title: "Operating Systems",
    star: <AiFillStar className="rating-star" />,
    reviews: "(390 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "3rd",
    semester: "5th semester",
    branch: "Computer Science",
  },
  {
    img: "",
    title: "Power Electronics",
    star: <AiFillStar className="rating-star" />,
    reviews: "(202 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "3rd",
    semester: "5th semester",
    branch: "Electrical Engineering",
  },
  {
    img: "",
    title: "Database Management Systems",
    star: <AiFillStar className="rating-star" />,
    reviews: "(319 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "3rd",
    semester: "5th semester",
    branch: "Information Technology",
  },
  {
    img: "",
    title: "Structural Analysis",
    star: <AiFillStar className="rating-star" />,
    reviews: "(178 reviews)",
    prevPrice: "10",
    newPrice: "5",
    year: "3rd",
    semester: "5th semester",
    branch: "Civil Engineering",
  },
];

export default data;
